---
- name: Install Apache on Amazon Linux
  hosts: all
  remote_user: ec2-user
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Install Apache on CentOS
      yum:
        name: httpd
        state: present
      when: 
        - ansible_facts['ansible_distribution'] == "CentOS"

    - name: Install Apache on Ubuntu
      package:
        name: apache2
        state: present
      when:
        - ansible_facts['ansible_distribution'] == "Ubuntu"

    - name: Start Apache on CentOS
      ansible.builtin.service:
        name: httpd
        state: started
      when:
        - ansible_facts['ansible_distribution'] == "CentOS"

    - name: Start Apache on Ubuntu
      ansible.builtin.service:
        name: apache2
        state: started
      when: 
        - ansible_facts['ansible_distribution'] == "Ubuntu"

    - name: Ensure Apache service is enabled and running on CentOS
      systemd:
        name: httpd
        enabled: yes
        state: started
      when: 
        - ansible_facts['ansible_distribution'] == "CentOS"

    - name: Ensure Apache service is enabled and running on Ubuntu 
      systemd:
        name: apache2
        enabled: yes
        state: started
      when: 
        - ansible_facts['ansible_distribution'] == "Ubuntu"

    - name: Copy website files on CentOS
      copy:
        src: index.html
        dest: /var/www/html/index.html
      when: ansible_facts['ansible_distribution'] == 'CentOS'

    - name: Copy website files on Ubuntu
      copy:
        src: index.html
        dest: /var/www/html/index.html
      when: ansible_facts['ansible_distribution'] == 'Ubuntu'

    - name: Restart Apache on CentOS 
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: 
        - ansible_facts['ansible_distribution'] == "CentOS"

    - name: Restart Apache on Ubuntu 
      ansible.builtin.service:
        name: apache2
        state: restarted
      when: 
        - ansible_facts['ansible_distribution'] == "Ubuntu"

