---
- name: Install and Configure Apache
  hosts: all
  remote_user: ec2-user
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install Apache
      package:
        name: "{{ 'httpd' if ansible_distribution == 'CentOS' else 'Ubuntu' }}"
        state: present

    - name: Start Apache
      ansible.builtin.service:
        name: "{{ 'httpd' if ansible_distribution == 'CentOS' else 'Ubuntu' }}"
        state: started

    - name: Ensure Apache service is enabled and running
      systemd:
        name: "{{ 'httpd' if ansible_distribution == 'CentOS' else 'Ubuntu' }}"
        enabled: yes
        state: started

    - name: Copy website files
      copy:
        src: index.html
        dest: "/var/www/html/index.html"

    - name: Restart Apache
      ansible.builtin.service:
        name: "{{ 'httpd' if ansible_distribution == 'CentOS' else 'Ubuntu' }}"
        state: restarted


