---
- name: Install Apache on Amazon Linux
  hosts: all
  remote_user: ec2-user
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Install Apache 
      yum:
        name: httpd
        state: present
      when: 
        - ansible_distribution == "CentOS" 
        - ansible_distribution == "Ubuntu"
  
    - name: Start Apache 
      ansible.builtin.service:
        name: httpd
        state: started
      when:
        - ansible_distribution == "CentOS" 
        - ansible_distribution == "Ubuntu"

    - name: Ensure Apache service is enabled and running 
      systemd:
        name: httpd
        enabled: yes
        state: started
      when: 
        - ansible_distribution == "CentOS" 
        - ansible_distribution == "Ubuntu"

    - name: Copy website files
      copy:
        src: index.html
        dest: /var/www/html/index.html
      when: 
        - ansible_distribution == "CentOS" 
        - ansible_distribution == "Ubuntu"

    - name: Restart Apache 
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: 
        - ansible_distribution == "CentOS" 
        - ansible_distribution == "Ubuntu"
